### ISSUE TITLE
Consider carefully before designing the product

### ISSUE THREAD

**Issue by EnziinSystem** [hailo-ai/hailo-rpi5-examples#4]
Please consider carefully before designing the product.

People at Halio or Raspberry should listen to the needs of users.

We need to use both SSD and AI together in a HAT, not choose one between the two.

Because the Pi-5 only has one free PCIe port, it had to be designed behind a PCI splitter like the ASMedia chip.

It is not useful to use an AI accelerator card with an operating system in an SD card.

**Comment by Gordon999** [comment]
May help...

https://forums.raspberrypi.com/viewtopic.php?t=371991#p2228665

**Comment by jdimpson** [comment]
I'm using the HAILO thingy and an M.2 NVME SSD right now, with the Pimoroni [NVME Base Duo](https://shop.pimoroni.com/products/nvme-base-duo-for-raspberry-pi-5). The RPI5 firmware needed to be updated in order to boot from an SSD over a PCIe switch--which meant I had to install Rasbian onto an SDCard to do the update--but it now boots and runs from the SSD and can run all the HAILO samples.

**Comment by giladnah** [comment]
Hi Guys, as said above. You can use Hailo and SSD together but currently available switches will force you to work in PCIe gen2. Everything should still work but the Hailo device performance will be reduced due to PCIe bottleneck.
If you hear of a new HAT which supports PCIe gen 3 please let me know.
I suggest moving this discussion to our community site: https://community.hailo.ai/
